# fly.toml app configuration file generated for social-healthspace on 2025-04-12T21:47:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "social-healthspace"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  ACCESS_TOKEN_EXPIRE_MINUTES = '30'
  API_V1_STR = '/api/v1'
  ENVIRONMENT = "production"
  JWT_ALGORITHM = 'HS256'
  PORT = "8080"
  PROJECT_NAME = 'Social HealthSpace'
  PYTHONUNBUFFERED = "1"
  VERSION = '1.0.0'
  # Database configuration
  POSTGRES_SERVER = "social-healthspace-db.internal"
  POSTGRES_PORT = "5432"
  POSTGRES_DB = "postgres"
  POSTGRES_USER = "postgres"
  POSTGRES_PASSWORD = "postgres"  # This will be overridden by the secret

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[http_service.tcp_ports]]
    port = 5432
    handlers = ["pg_tls"]

[metrics]
  port = 8080
  path = "/metrics"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
  disk_gb = 40
