# fly.toml app configuration file generated for social-healthspace on 2025-04-11T12:29:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "social-healthspace"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  ENVIRONMENT = "production"
  DATABASE_URL = { from = "DATABASE_URL" }
  JWT_SECRET_KEY = { from = "JWT_SECRET_KEY" }
  JWT_ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "30"
  PROJECT_NAME = "Social HealthSpace"
  VERSION = "1.0.0"
  API_V1_STR = "/api/v1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 