[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv venv",
    ". venv/bin/activate",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = ". venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT" 